/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * 
 * @author HP
 * 
 */
import java.sql.Connection;
import dou.Connectionprovider;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class AddUser extends javax.swing.JFrame {
    public String emailPattern="^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
public String mobileNumberPattern="^[0-9]*$";
    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        comboUserType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addUserSaveBtn = new javax.swing.JButton();
        addUserBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 40, 157, 49));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 154, 51, -1));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 193, 230, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 85, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 281, 248, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Phone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 330, 108, -1));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 361, 248, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 401, 138, -1));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 438, 249, -1));

        comboUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Customer", "Delivery Boy", " " }));
        getContentPane().add(comboUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 111, 265, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("User Type");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 73, 99, 26));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 193, 285, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Password :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 145, 98, 42));

        addUserSaveBtn.setText("Save");
        addUserSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserSaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addUserSaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 252, -1, -1));

        addUserBackBtn.setText("Back");
        addUserBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addUserBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void addUserSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserSaveBtnActionPerformed
        // TODO add your handling code here:
          String userRole=(String) comboUserType.getSelectedItem();
        String name= txtname.getText();
        String email= txtEmail.getText();
        String mobileNumber= txtPhone.getText();
        String password= txtPassword.getText();
        String address= txtAddress.getText();
        if(name.equals(""))
        {
            JOptionPane.showMessageDialog(null,"This field can't empty");
        }

        else if(email.equals(""))
        {
            JOptionPane.showMessageDialog(null,"This field can't empty");
        }
        else if(!email.matches(emailPattern))
        {
            JOptionPane.showMessageDialog(null,"Invalid Email Address");
        }
        else if(password.equals(""))
        {
            JOptionPane.showMessageDialog(null,"This field can't empty");
        }
        else if(address.equals(""))
        {
            JOptionPane.showMessageDialog(null,"This field can't empty");
        }

        else if(mobileNumber.equals(""))
        {
            JOptionPane.showMessageDialog(null,"This field can't empty");
        }
        else
        {
          try{
              Connection con=Connectionprovider.getCon();
              PreparedStatement ps =con.prepareStatement("insert into appuser (userRole,name,email,mobileNumber,password,address) values(?,?,?,?,?,?) ");
              ps.setString(1,userRole);
              ps.setString(2,name);
              ps.setString(3,email);
              ps.setString(4,mobileNumber);
              ps.setString(5,password);
              ps.setString(6,address);
              ps.executeUpdate();
              JOptionPane.showMessageDialog(null, "User Succesfully Added");
              setVisible(false);
              new AddUser().setVisible(true);
          }
          catch(Exception e)
          {
                JOptionPane.showMessageDialog(null, e);
              
          }
        }
    }//GEN-LAST:event_addUserSaveBtnActionPerformed

    private void addUserBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBackBtnActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new ViewUser().setVisible(true);
    }//GEN-LAST:event_addUserBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserBackBtn;
    private javax.swing.JButton addUserSaveBtn;
    private javax.swing.JComboBox<String> comboUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
