
import dou.Connectionprovider;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogIn = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        loginEmail = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        PasswordField1 = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        loginBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogIn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LogIn.setForeground(new java.awt.Color(255, 255, 255));
        LogIn.setText("Log In");
        getContentPane().add(LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 154, -1));

        emailInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 251, 42));

        loginEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginEmail.setForeground(new java.awt.Color(255, 255, 255));
        loginEmail.setText("Email");
        getContentPane().add(loginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 80, -1));

        Password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 92, 33));

        PasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(PasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 251, 37));

        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginBtn.setText("LogIn");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        loginBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thermometer-1539191_1920.jpg"))); // NOI18N
        loginBackground.setText("jLabel1");
        loginBackground.setMaximumSize(new java.awt.Dimension(800, 700));
        loginBackground.setMinimumSize(new java.awt.Dimension(800, 700));
        getContentPane().add(loginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String email=emailInput.getText();
          String password=PasswordField1.getText();
          int temp=0;
           try {
           
   Connection con = Connectionprovider.getCon();
    Statement st= con.createStatement();
    ResultSet rs=st.executeQuery("select *from appuser where email= '"+email+"' and password='"+password+"'  ");
    while(rs.next())
    {
        temp=1;
        if(rs.getString("userRole").equals("Admin"))
        {
            setVisible(false);
            new AdminDasboard(email).setVisible(true);
        }
        else 
        {
            setVisible(false);
            new PharmacistDasboard(email).setVisible(true);
            
        }
    }
    if(temp==0)
    {
     JOptionPane.showMessageDialog(null,"Incorrect UserName or Password");
    }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
           
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you want to close the application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_closebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogIn;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JButton closebtn;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel loginBackground;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginEmail;
    // End of variables declaration//GEN-END:variables
}
