/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class SellMedicine extends javax.swing.JFrame {

    /**
     * Creates new form SellMedicine
     */
    public SellMedicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        medicineSearchId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        searchMedicine = new javax.swing.JButton();
        billButton = new javax.swing.JButton();
        addMedicineToSellList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        medicineId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        medicineName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        companyNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pricePerUnitField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        numberOfMedicineField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sell Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 370, -1));

        medicineSearchId.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        getContentPane().add(medicineSearchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 260, 30));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel2.setText("Medicine ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        searchMedicine.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        searchMedicine.setText("Search");
        searchMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMedicineActionPerformed(evt);
            }
        });
        getContentPane().add(searchMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        billButton.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        billButton.setText("Bill");
        billButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billButtonActionPerformed(evt);
            }
        });
        getContentPane().add(billButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 620, -1, -1));

        addMedicineToSellList.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        addMedicineToSellList.setText("Add");
        getContentPane().add(addMedicineToSellList, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine ID", "Name", "Company Name", "Price Per Unit", "Number of Units", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 560, 340));

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        jLabel5.setText("Medicine ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        medicineId.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        getContentPane().add(medicineId, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 200, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, -1, -1));

        medicineName.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        getContentPane().add(medicineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 200, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        jLabel4.setText("Company Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, -1));

        companyNameField.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        getContentPane().add(companyNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 200, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        jLabel6.setText("Price Per Unit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, -1, -1));

        pricePerUnitField.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        getContentPane().add(pricePerUnitField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 200, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        jLabel7.setText("Number of Medicine");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));

        numberOfMedicineField.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        getContentPane().add(numberOfMedicineField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 200, -1));

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        jLabel8.setText("Total Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 230, 90, -1));

        totalField.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        getContentPane().add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 200, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMedicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMedicineActionPerformed

    private void billButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMedicineToSellList;
    private javax.swing.JButton billButton;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField medicineId;
    private javax.swing.JTextField medicineName;
    private javax.swing.JTextField medicineSearchId;
    private javax.swing.JTextField numberOfMedicineField;
    private javax.swing.JTextField pricePerUnitField;
    private javax.swing.JButton searchMedicine;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
