/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author User
 */
public class Stock extends javax.swing.JPanel {

    /**
     * Creates new form Stock
     */
    public Stock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addProduct = new javax.swing.JButton();
        updateProduct = new javax.swing.JButton();
        deleteProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockTable = new javax.swing.JTable();
        newProductName = new javax.swing.JTextField();
        newProductQuantity = new javax.swing.JTextField();
        newProductPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        jLabel1.setText("Stock Products");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 48, -1, -1));

        addProduct.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        addProduct.setText("Add Product");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });
        add(addProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        updateProduct.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        updateProduct.setText("Update Product");
        add(updateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        deleteProduct.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        deleteProduct.setText("Delete Product");
        add(deleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        stockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(stockTable);
        if (stockTable.getColumnModel().getColumnCount() > 0) {
            stockTable.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, 380));

        newProductName.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        newProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductNameActionPerformed(evt);
            }
        });
        add(newProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 180, -1));

        newProductQuantity.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        add(newProductQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 160, -1));

        newProductPrice.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        add(newProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 180, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setText("Quantity");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel4.setText("Price");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductActionPerformed

    private void newProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JButton deleteProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newProductName;
    private javax.swing.JTextField newProductPrice;
    private javax.swing.JTextField newProductQuantity;
    private javax.swing.JTable stockTable;
    private javax.swing.JButton updateProduct;
    // End of variables declaration//GEN-END:variables
}
