/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.sql.Connection;
import dou.Connectionprovider;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.TableModel;

public class ViewUser extends javax.swing.JFrame {

    private String username = "";

    /**
     * Creates new form ViewUser
     */
    public ViewUser() {
        initComponents();
    }

    public ViewUser(String tempUsername) {
        initComponents();
        username = tempUsername; //Email of User
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewUserHeaderLabel = new javax.swing.JLabel();
        viewUserBackBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewUserTable = new javax.swing.JTable();
        addUserBtn = new javax.swing.JButton();
        updateUserBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewUserHeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        viewUserHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewUserHeaderLabel.setText("View Users");
        viewUserHeaderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(viewUserHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 32, 197, 37));

        viewUserBackBtn.setText("Back");
        viewUserBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserBackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewUserBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 17, 95, -1));

        viewUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Phone", "Address"
            }
        ));
        viewUserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewUserTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewUserTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 101, 838, 345));

        addUserBtn.setText("AddUser");
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        updateUserBtn.setText("Update User");
        updateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) viewUserTable.getModel();
        try {
            Connection con = Connectionprovider.getCon();
          Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select *from appuser");
            while (rs.next()) {
              
                model.addRow(new Object[]{rs.getString("appuser_pk"),rs.getString("name"),rs.getString("email"),rs.getString("mobileNumber"),rs.getString("address")});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void viewUserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUserTableMouseClicked
        // TODO add your handling code here:
         
        int index= viewUserTable.getSelectedRow();
        TableModel model= viewUserTable.getModel();
        String id= model.getValueAt(index,0).toString();

        String usernameTable= model.getValueAt(index, 2).toString();
        
        if(username.equals(usernameTable))
        {
            JOptionPane.showMessageDialog(null,"You can' delete your own Account");
        }
        else 
        {
            int a=JOptionPane.showConfirmDialog(null,"Do you want to Delete this Account?","Select",JOptionPane.YES_NO_OPTION);
          if(a==0)
          {
              try{
              Connection con=Connectionprovider.getCon();
              PreparedStatement ps=con.prepareStatement("delete from appuser where appuser_pk=?");
              ps.setString(1,id);
              ps.executeUpdate();
              JOptionPane.showMessageDialog(null, "Account Deleted Succesfully.");
              setVisible(false);
              new ViewUser(username).setVisible(true);
              }
              catch(Exception e)
              {
                  JOptionPane.showMessageDialog(null, e);
              }
          }
        }
        
        
    }//GEN-LAST:event_viewUserTableMouseClicked

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddUser().setVisible(true);
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void viewUserBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUserBackBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AdminDasboard(username).setVisible(true);
    }//GEN-LAST:event_viewUserBackBtnActionPerformed

    private void updateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserBtnActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new UpdateUser().setVisible(true);
    }//GEN-LAST:event_updateUserBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateUserBtn;
    private javax.swing.JButton viewUserBackBtn;
    private javax.swing.JLabel viewUserHeaderLabel;
    private javax.swing.JTable viewUserTable;
    // End of variables declaration//GEN-END:variables
}
